### PR TITLE
Added equivalent ChimeraX projection functions as an alternative to PyMol projections

### PR DESCRIPTION
**Pull request by darianyang**
Hello,

Great work on this package! I'm using it for my project and noticed that the protein structure projection functions were only compatible with PyMol, I've added and tested an equivalent set of functions that work with ChimeraX. See below for a comparison. I've tried to keep the same code style and projection scheme originally used with the pymol-based functions.

Created using `pymol_projections.project_pymol_top_features` and `pymol_projections.project_pymol_per_res_scores`:
pymol

Created using `chimerax_projections.project_chimerax_top_features` and `chimerax_projections.project_chimerax_per_res_scores`:
chimeraX

### CODE REVIEW

**Comment by RMCrean** [comment]
Thanks very much for this PR, from a first glance it looks great, and I would be very happy to add it to KIF. 

I will review and test the code on either Monday or Tuesday evening and get back to you with any comments or changes etc.. I would like to add. 

Thanks, and speak soon! 
Rory

**Review by RMCrean — APPROVED** [review]
Thanks for working on this, I'll add a comment on the PR shortly

**Comment by RMCrean** [comment]
Thanks again for your work, I've had a chance to test this now (had never actually used ChimeraX before so that was cool) and I can see it works nicely. 

I've made 2 commits to the code: 

The first commit essentially adds the extra dependency you need for your module (biopython) to setup.py and then includes the module in the mkdocs site, e.g.: https://kamerlinlab.github.io/KIF/

For the second commit I noticed we were using the same helper functions so to avoid duplication I've made a new module (project_structure_utils.py - not the best name I know), and now both pymol_projections.py and chimerax_projections.py pull the shared code from there. 

I've made sure these changes still give the same results on my test dataset, (but do feel free to test these changes for yourself). 

Please let me know if you're happy with this and if so I'll merge the branch and add an updated version to PyPI. I will also add an explanation in the README and in one of the tutorials that this is now possible

**Comment by darianyang** [comment]
Thanks for the updates! 

Looks good, I agree that having separate common functions would be best practice. 

One thing that I want to potentially update: I didn't realize that biopython wasn't already a dependency, the use of biopython is to get coordinates since ChimeraX cylinders are defined by xyz positions instead of atom names. This functionality can probably be done using MDAnalysis, which is already a dependency, thus reducing bloat. If it's okay with you, I'll try this out and get back to you soon.

**Comment by darianyang** [comment]
Done! Just got rid of the biopython dependency, sorry I didn't catch that before, personally I think the less dependencies the better.

**Comment by RMCrean** [comment]
Great, thanks for that! I will merge the PR now then. :)

**Comment by RMCrean** [comment]
I can confirm the new version is now available via pypi and information about the new features from this PR is in the README and the tutorials. 

Thanks again for your work on this :)

**Pull request merged**
